Repository cms-sw/cms-bot, pull requests merged in 2018-04, with the labels that each got.

#969 comparisons: map updates; reco comparisons/validate.C add recent muon variables, PF debug plots, more strict configuration
  comparisons/matrix_RE.txt
  comparisons/validate.C
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#968 Changed name for DQM/Phase2OuterTracker
  categories_map.py
Labels: dqm-pending, externals-approved, orp-pending, pending-signatures, tests-pending

#970 Remove 'ghellwig'.
  categories.py
  category-watchers.yaml
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#971 Updated cmsdist repo permissions: Removed BrunoCoimbra and added lecriste
  cmsdist_merge_permissions.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#973 Update watchers.yaml
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#976 Update for ebrondol
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#972 DQMHistoSizes: make output more detailed
  logRootQA.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#977 allow Alberto Sanchez (GEN L3) to sign PR in CMSSW
  categories.py
Labels: externals-approved, fully-signed, orp-pending, tests-pending

#980 Fix sign in DQMHistoSizes
  logRootQA.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#978 Add a 2018 premixing workflow to PR tests
  cmssw-pr-test-config
Labels: externals-pending, orp-pending, pending-signatures, tests-pending
