Repository cms-sw/cms-bot, pull requests merged in 2018-06, with the labels that each got.

#991 add RecoBTag/TensorFlow to reconstruction category
  categories_map.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#992 Update openstack image names for CC7 and SLC6
  openstack/hg/os.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#993 Adding PoHsun as AlCa L2
  categories.py
Labels: externals-approved, fully-signed, orp-approved, tests-pending

#994 add CTPPS db package
  categories_map.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#996 Update groups.yaml, adding Heiner Tholen
  groups.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#995 Update watchers.yaml for makortel
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#997 Add Geometry MTD packages to the geometry category
  categories_map.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#999 add clelange as watcher for several JME JMAR related packages
  watchers.yaml
Labels: externals-approved, fully-signed, orp-pending, tests-pending

#998 Add the new CondFormats/SiPixelTransient package, and assign both db and reco as owners
  categories_map.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1000 Packages for watch by jan-kaspar
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1001 Auto-discover CC7 and SLC6 images available for DMWM
  openstack/hg/os.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-pending
