Repository cms-sw/cms-bot, pull requests merged in 2018-07, with the labels that each got.

#1002 add hgcal unpacker to categories
  categories_map.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1003 adjustments for drkovalskyi
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1004 Update categories.py
  categories.py
Labels: externals-approved, fully-signed, orp-pending, tests-pending

#1005 Update categories.py
  categories.py
Labels: externals-approved, fully-signed, orp-pending, tests-pending

#1006 added @kpedro88 as release manager
  categories.py
Labels: externals-approved, fully-signed, orp-pending, tests-pending

#1007 Replacing Virginia by new DQM Offline manager Andrius Kirilovas
  categories.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1008 adding Tongguang Cheng as L2 AlCa
  categories.py
Labels: externals-approved, fully-signed, orp-approved, tests-pending

#1010 Removed Gianluca from AlCa category
  categories.py
Labels: externals-approved, fully-signed, orp-pending, tests-pending

#1011 Update gh-teams.py
  gh-teams.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1013 Update categories.py
  categories.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending
