Repository cms-sw/cms-bot, pull requests merged in 2019-12, with the labels that each got.

#1230 reco comparisons: workflow map updates
  comparisons/matrix_RE.txt
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1231 Added external build stats for PR tests
  pr_testing/test_multiple_prs.sh
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#1232 Watch a few more packages - K.Hatakeyama
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1234 Multi line comment changes rebased
  process_pr.py
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#1064 Add "heterogeneous" category, packages and maintainers
  categories.py
  categories_map.py
Labels: comparison-pending, externals-approved, fully-signed, orp-approved, tests-approved

#1235 Add new package Heterogeneous/CUDATest to the heterogeneous category
  categories_map.py
Labels: comparison-pending, externals-approved, fully-signed, orp-approved, tests-approved

#1236 Add Silvio Donato as new release manager
  categories.py
Labels: comparison-pending, externals-approved, fully-signed, orp-approved, tests-approved

#1237 Add DQMServices/Demo
  categories_map.py
Labels: comparison-pending, externals-approved, fully-signed, orp-approved, tests-approved

#1238 Update watchers.yaml for makortel
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1240 Enable new pkgtools build monitoring
  condor/tests/node-check.py
  monitor_workflow.py
  pr_testing/test_multiple_prs.sh
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-rejected

#1241 reco comparisons updates for HGCAL
  comparisons/validate.C
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1242 added helper scirpt to build and test cms prs
  common/get_config_map_line.sh
  common/get_cpu_number.sh
  pr_testing/_helper_functions.sh
  pr_testing/get_source_flag_for_cmsbuild.sh
  test-prs.sh
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1243 Mark CMSSW_8_0_34_UL/slc7_amd64_gcc530 as production release
  releases.map
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1244 Add Silvio Donato as L2 operation
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending
