Repository cms-sw/cms-bot, pull requests merged in 2019-11, with the labels that each got.

#1219 add ONNXRuntime packages to reconstruction and analysis
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1220 update reco comparisons: new products, automate handling of range scans
  comparisons/validate.C
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1218 Add robervalwalsh as watcher for Strips packages
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1223 Remove geoff-smith from watchers.yaml
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1226 Update watchers.yaml
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#1224 Adding new packages for TrackerPhase2 DQM and Validation
  categories_map.py
Labels: comparison-pending, externals-pending, orp-approved, pending-signatures, tests-started

#1227 remove cmssw/externals/arch/lib for PR testing
  pr_testing/test_multiple_prs.sh
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, requires-external, tests-rejected

#1228 update mapping file for reco comparisons
  comparisons/matrix_RE.txt
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved
