Repository cms-sw/cms-bot, pull requests merged in 2019-08, with the labels that each got.

#1180 add BigProducts/Simulation to simulation category
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1179 reco comparisons: add a maping for D46, only for ttbar wf 22034
  comparisons/matrix_RE.txt
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1181 Update watchers.yaml
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1182 Add module to Watchlist
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1183 reco comparisons: update maps for Run3 workflows
  comparisons/matrix_RE.txt
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1184 Update my watchlist
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1185 Add new pdmv convener to categories definition
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1186 Add RecoBTag/PixelCluster in support of cmssw PR 27738
  categories_map.py
Labels: comparison-available, externals-pending, orp-approved, pending-signatures, tests-approved

#1187 add Felice Pantaleo and Marco Rovere to PR test
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1190 Update categories_map.py
  categories_map.py
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1189 allow kpedro88 to sign for operations
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1192 Addition to the list of watchers
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#1193 Removing 'gudrutis' from cms-bot
  categories.py
  gh-teams.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1195 Add RecoTracker/MkFit package to reconstruction
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1196 [Python3] run python3 tests for PRs
  pr_testing/test_multiple_prs.sh
  report-pull-request-results.py
Labels: comparison-pending, externals-approved, fully-signed, orp-pending, requires-external, tests-approved

#1197 run static checks with -DEDM_ML_DEBUG -w for PR tests
  pr_testing/test_multiple_prs.sh
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, requires-external, tests-approved
