Repository cms-sw/cms-bot, pull requests merged in 2019-05, with the labels that each got.

#1132 Update gh-teams.py
  gh-teams.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1131 Update categories.py
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1136 reco comparisons updates: new plots and updated workflow map
  comparisons/matrix_RE.txt
  comparisons/validate.C
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#1137 add me to RecoHGCal package
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1140 report-summary-merged-prs includes cmsdist PRs data
  github_utils.py
  report-summary-merged-prs
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1139 Added RecoTauTag/TrainingFiles under reconstruction
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, reconstruction-pending, tests-pending

#1142 Addition of timing and memory check if available in PR matrix test
  pr_testing/test_multiple_prs.sh
  run-pr-tests
Labels: comparison-pending, externals-approved, fully-signed, orp-pending, tests-approved

#1143 Added support for changed DQM bbb comparison tool
  run-pr-comparisons
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1144 Escape an argument to support space separated values in DQM bin by bin tool
  run-pr-comparisons
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#1147 Update categories_map.py
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1148 Report merged PR numbers and ignore private merges
  common/github_reports.sh
  pr_testing/get-merged-prs.py
  pr_testing/test_multiple_prs.sh
  report-pull-request-results.py
Labels: comparison-pending, externals-approved, fully-signed, orp-pending, requires-external, tests-approved
