Repository cms-sw/cms-bot, pull requests merged in 2019-04, with the labels that each got.

#1108 reco comparisons: plots for PPS protons
  comparisons/matrix_RE.txt
  comparisons/validate.C
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1109 A fix to pick the correct version of DQM bin by bin comparison tool.
  run-pr-comparisons
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1113 Add L1THGCalUtilities package
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1112 Add TimeMemorySummary.py as default option for every runTheMatrix.py workflow
  run-pr-tests
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1114 Revert "Add TimeMemorySummary.py as default option for every runTheMatrix.py workflow"
  run-pr-tests
Labels: comparison-pending, externals-pending, orp-approved, pending-signatures, tests-pending

#1117 Add new package Validation/MtdValidation in support of cmssw PR 26347
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1120 Add Chris West as L2 AlCa
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1121 Add docker image for powerpc
  config.map
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1123 Add Tapio Lampen as AlCaDB convener
  categories.py
Labels: alca-approved, comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1125 Update watchers.yaml
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1126 Temporarily move the production architecture for 8_0_X and 9_4_X to slc7
  config.map
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1127 Revert "Temporarily move the production architecture for 8_0_X and 9_4_X to slc7"
  config.map
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1128 update in reco comparisons: D41 wfs map; muon nDigisInRange plot
  comparisons/matrix_RE.txt
  comparisons/validate.C
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1129 adding jshlee to gem watchers
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending
