Repository cms-sw/cms-bot, pull requests merged in 2019-07, with the labels that each got.

#1161 remove TaiSakuma from watchers.yaml
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1162 Update templat and remove write filter condition for ib-matrix index
  es/templates/cmssdt-runthematrix-data.json
  es_relval_log.py
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1163 Dynamic mapping for new fields
  es/templates/cmssdt-runthematrix-data.json
  es_relval_log.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1164 reco comparisons: updated map files
  comparisons/matrix_70X.txt
  comparisons/matrix_RE.txt
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1167 Add account sbein as new fastsim review responsible
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1165 Add elasticsearch reindexing script to cms-bot
  es_reindex_indexes_with_pattern.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1171 reco comparisons: rename 2023 to 2026 for phase-2 workflows in 110X
  comparisons/matrix_RE.txt
Labels: comparison-available, externals-pending, orp-approved, pending-signatures, tests-approved

#1174 update list of watched packages - deguio
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1172 Add andrzejnovak to btv
  groups.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1173 Subscribing to btv-pog PR updates
  groups.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1168 Syncronize github_webhook with cmssdt-web/cgi_bin/github_webhook and make Python 3 compatibility changes.
  github_webhook
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1175 Update watchers.yaml
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1176 clelange watch HGCal-related packages
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1177 added the HGCalSimAlgos package to upgrade and simulation categories
  categories_map.py
Labels: comparison-pending, externals-pending, orp-approved, pending-signatures, tests-started

#1178 Remove test index creation
  es_relval_log.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started
