Repository cms-sw/cms-bot, pull requests merged in 2019-03, with the labels that each got.

#1097 Update system info
  jenkins/system-info.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1099 Add packages to package map for Phase2 Tracker DTC cabling map (cmssw PR #26029)
  categories_map.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1100 Update docker_launcher.sh
  docker_launcher.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1098 reco comparisons: plots for new products/variables including bParking/lowPt electrons
  comparisons/validate.C
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1102 In support of cmssw#26187, add CommonTools/BaseParticlePropagator to fastsim and reconstruction
  categories_map.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1104 Update btv group
  groups.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1103 Updates in support of CMSSW #25495
  categories_map.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1105 Add TICL package under upgrade
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending, upgrade-pending

#1093 Adding DQM bin by bin comparison tool
  run-pr-comparisons
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending
