Repository cms-sw/cms-bot, pull requests merged in 2020-07, with the labels that each got.

#1337 Assign "L1TTrackMatch" and "Phase2L1ParticleFlow" to upgrade and l1
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1338 add jpata to reco L2
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1339 Add gouskos and mariadalfonso as xpog
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1340 reco comparisons: plots for JPT jets; packed candidates from heavy ion miniAOD
  comparisons/validate.C
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1341 Check tag pattern before using it
  create-new-data-pr.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1342 merge docs category with core
  categories.py
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1343 reco comparisons updates: new map, chi2 variables for HI
  comparisons/matrix_RE.txt
  comparisons/validate.C
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1344 Add RecoHGCal for user rovere
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1346 Add Qiang Li as new release manager
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1347 fixed categories for qliphy
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1348 enable threaded relvals for cc8 and gcc10
  RelValArgs.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1349 Update watchers.yaml
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1350 Categories: Remove myself from DQM L2s.
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1351 Add case statement to use different workflows for CMSSW_11_2_*
  schedule-additional-tests
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started
