Repository cms-sw/cms-bot, pull requests merged in 2020-05, with the labels that each got.

#1294 Adding a list of packge for abdoulline to watchers.yaml
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1293 adding new GEN L2
  categories.py
  gh-teams.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1295 Add list of packages to watch by Sergio Lo Meo
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1297 Reducing watch list for kreczko (-DQM, -TOP)[watchers.yaml]
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1296 Update watchers.yaml
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1292 reco comparisons: TICL monitoring: tracksters with multiclusters, TICL and PF Candidates
  comparisons/validate.C
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1298 remove GurpreetSinghChahal for now. He need to first accept the membership
  gh-teams.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1299 Code check fix
  run-pr-code-checks
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1302 reco comparisons: add map entries for Run2 UL reminiAOD workflows
  comparisons/matrix_RE.txt
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#1303 Update categories.py
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1305 Update gh-teams.py
  gh-teams.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1306 Add mmusich in TRIGGER_PR_TESTS
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#1308 CommonTools/Egamma in reco (moved from RecoEgamma/EgammaTools)
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1310 reco comparisons map update: add wf 23234.1001 TTbar_14TeV OldDigi_2026D49
  comparisons/matrix_RE.txt
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1311 Add SimCalorimetry/HGCalAssociatorProducers to simulation and upgrade
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1309 Filter 'edm::ConcurrentHadronizerFilter<Pythia8Hadronizer' in modules2statics report
  run_clang_static_analysis
  statics-filter1.txt
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending
