Repository cms-sw/cms-bot, pull requests merged in 2020-09, with the labels that each got.

#1373 Produce text reports from run-ib-igprof
  run-ib-igprof
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1374 Get the Igprof output txt filenames correct
  run-ib-igprof
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1377 Use cmssw-pr-test-config to select profiling workflow
  cmssw-pr-test-config
  schedule-additional-tests
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1375 updates in reco comparisons: plots for new products, minor style updates
  comparisons/validate.C
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1378 Fix var name in PROFILING_WORKFLOWS loop.
  schedule-additional-tests
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1379 bugfix in process name used for reminiAOD for HI MC reco comparisons mapping
  comparisons/matrix_RE.txt
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#1372 Add PR comment command "enable profiling" to add a profiling test and comparison to PR.
  pr_testing/test_multiple_prs.sh
  process_pr.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#1376 Generate the RECO event loop summary using the igprof text reports
  run-ib-igprof
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1371 added gurpreet, removed qiang, removed myself from watching
  categories.py
  gh-teams.py
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1382 Fix bug in run-igprof-fix
  run-ib-igprof
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1383 run-ib-igprof: Remove escapes from $ in awk command
  run-ib-igprof
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1381 Add PhysicsTools/IsolationAlgos to reconstruction
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1384 Update of watch directories for jan-kaspar
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1380 For profiling add symbolic links so Igprof and Circles files can be read
  jenkins-artifacts
  pr_testing/test_multiple_prs.sh
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-approved

#1385 Adding Ernesta Petraityte as dqm
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1387 Added pixel-offline watchers group
  groups.yaml
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1388 Add YuanChao to CMSSW L2 list for AlCa
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1389 Add RecoLocalTracker/SiPhase2VectorHitBuilder to reconstruction and upgrade categories
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending
