Repository cms-sw/cms-bot, pull requests merged in 2020-03, with the labels that each got.

#1269 Add a couple of packages for rovere
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#1270 add Stefano Belforte ad Daina DIrmaite (CRAB people) to those who can…
  cmsdist_merge_permissions.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1271 Update categories_map.py
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#1272 Update categories_map.py
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#1274 add category and watcher for SONIC package
  categories_map.py
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1275 Add SimCalorimetry package
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1277 Update of categories.py as asked by PPD
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1279 Just removed my self from some old contributing packages
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1280 updates in reco Comparisons: monitor PUPPI jets
  comparisons/matrix_RE.txt
  comparisons/validate.C
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1281 Update categories_map.py
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1282 Add fabiocos to the watchers list
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1278 Clean up old release managers
  categories.py
  milestones.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1273 L1TTrackerDTC
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending
