Repository cms-sw/cms-bot, pull requests merged in 2020-11, with the labels that each got.

#1409 reco comparisons: add maps for Run3/2021 HI MC workflows
  comparisons/matrix_RE.txt
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1410 use commit status for code-checks
  cms_static.py
  common/github_reports.sh
  docker_launcher.sh
  pr_testing/test_multiple_prs.sh
  process_pr.py
  run-pr-code-checks
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1411 Added Ram Krishna Sharma to the watcher list of EGamma related activi…
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1412 added run das queries test for PRs; reset statues on rerun
  github_utils.py
  mark_commit_status.py
  pr_testing/run-das-query.py
  pr_testing/test_multiple_prs.sh
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#1415 Update watched packages for user riga.
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1414 Run edmEventSize on step3 and step4 root files produced by running igprof on high pileup workflow 23434.21 and save output.
  run-ib-igprof
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1416 Fix typo in run-ib-igprof. Fix root file name which does not have underscore.
  run-ib-igprof
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#1417 build one of the two geant IBs today
  config.map
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1419 add checks for failing reco comparisons
  comparisons/validate.C
  logRootQA.py
  run-pr-comparisons
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1413 Run edmEventSize on root files produced by igprof workflow and save to compare with same profiling PR's
  comparisons/compareProducts.awk
  comparisons/compareProducts.sh
  pr_testing/test_multiple_prs.sh
  run-pr-comparisons
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1420 extend ROOTFileChecks to reminiAOD and data reco workflows
  logRootQA.py
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#1421 remove DataFormats/NanoAOD from the reco category
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1422 reco comparisons updates for: TICL plots; DD4HEP short matrix wfs
  comparisons/matrix_RE.txt
  comparisons/validate.C
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1423 Move WEB to DEPS before deletion and rename packages to package.json
  build-cmssw-ib-with-patch
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, requires-external, tests-rejected

#1424 Stop running monitor on arm
  RelValArgs.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1425 Bring the old file structure for DEPS folder
  build-cmssw-ib-with-patch
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1426 Watch L1T packages
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1428 remove deguio from watchers
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1429 new release cycle 11.3.X added
  config.map
  forward_ports_map.py
  milestones.py
  releases.map
  releases.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1427 Updates for pixel-offline
  groups.yaml
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1431 use gcc9 for 11.2.X
  config.map
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending
