Repository cms-sw/cms-bot, pull requests merged in 2020-12, with the labels that each got.

#1433 reco comparisons driver: check that both input root files are available before running validate.C
  comparisons/validateJR.sh
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#1434 Remove tocheng from alca L2 list
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1430 get product comparisons for all root files; clean up debugs in logRootQA.py
  logRootQA.py
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#1435 Only update status of main PR for which the tests were started
  common/github_reports.sh
  pr_testing/test_multiple_prs.sh
  process_pr.py
  tests/test_config-map.py
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1436 treat QALOG as a text file in run-pr-comparisons
  run-pr-comparisons
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-rejected

#1432 reduce pr test messages and make use of commit status
  github_utils.py
  pr_testing/test_multiple_prs.sh
  process_pr.py
  report-pull-request-results.py
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1439 add individual unit tests logs
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#1441 Change ES index and doc name for externals stats
  es_utils.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1444 Fix typo
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1443 Each test to add its own result.
  common/github_reports.sh
  pr_testing/_helper_functions.sh
  pr_testing/test_multiple_prs.sh
  report-pull-request-results.py
  run-igprof-pr
  run-pr-comparisons
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1447 Include relval and addon failed tests links
  report-pull-request-results
  report-pull-request-results.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1448 include the relval exception in the report
  report-pull-request-results.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1438 Move CommonTools/TriggerUtils from reco to hlt and l1
  categories_map.py
Labels: externals-approved, fully-signed, hlt-approved, l1-approved, orp-pending, reconstruction-approved, tests-approved

#1453 use PR number in bot status to distinguish b/w diff prs with same commit
  pr_testing/test_multiple_prs.sh
  process_pr.py
  run-pr-code-checks
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#1456 reco comparisons: matrix short name mapping update
  comparisons/matrix_RE.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-approved
