Repository cms-sw/cms-bot, pull requests merged in 2020-01, with the labels that each got.

#1199 Add permissions to "tulamor" user
  categories.py
  gh-teams.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1245 Add core L2 categories for makortel
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1246 Add makortel to CMSSW_ISSUES_TRACKERS
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1247 update GPU workflows
  cmssw-pr-test-config
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1248 Remove unused getParamDumper broken by llvm/clang 9
  run_clang_static_analysis
  run_class_dumper.sh
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#1249 Add changes for recursive clone of PR repos
  pr_testing/get_source_flag_for_cmsbuild.sh
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#1251 remove lina
  cmsdist_merge_permissions.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1253 Add FWCore/SharedMemory to core
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1254 assign dqm for DPGAnalysis/HcalTools package
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1255 Added special CMSSW_11_1_Patatrack_X IB
  config.map
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1252 Add one status per tests
  pr_testing/test_multiple_prs.sh
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1257 Exernals stats on Elastic (rebased)
  es_externals_stats.py
  es_utils.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1258 reco comparisons: monitor hcal reduced hits in miniAOD; map entry for 136.793_RunDoubleEG2017C
  comparisons/matrix_RE.txt
  comparisons/validate.C
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved
