Repository cms-sw/cms-bot, pull requests merged in 2020-04, with the labels that each got.

#1284 Replace fabiocos with dpiparo as CMSSW ORP/L1
  categories.py
Labels: comparison-pending, externals-approved, fully-signed, orp-approved, tests-started

#1283 updates in reco comparisons
  comparisons/matrix_RE.txt
  comparisons/validate.C
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1285 Added new dataformat packages for L1 and Upgrade
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1286 Added L1Trigger/TrackFindingTMTT under L1 categoriy
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1287 Add packages to watchlist
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1288 Add Heterogeneous-related folders for rovere
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1290 Update packages followed by battibass
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1289 check for static check logs for build errors
  pr_testing/test_multiple_prs.sh
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#1291 updated rucio config
  rucio/rucio.cfg
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending
