Repository cms-sw/cms-bot, pull requests merged in 2020-10, with the labels that each got.

#1390 Create TkDQM group and add it to watchers
  groups.yaml
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1391 Correct case of username yuanchao
  categories.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1392 Update watchers.yaml
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1393 Add CUDADataFormats/StdDictionaries for heterogeneous category
  categories_map.py
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1397 add myself as watcher
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1399 add swertz to watchers.yaml
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1402 upload cms externals for PR tests
  pr_testing/test_multiple_prs.sh
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1403 reco comparisons: new plots for HI miniAOD
  comparisons/validate.C
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#1404 Add CalibPPS/AlignmentRelative to alca
  categories_map.py
Labels: comparison-pending, externals-pending, orp-approved, pending-signatures, tests-started

#1401 Replace L1 secondary signature.
  categories.py
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#1407 Update watchers.yaml
  watchers.yaml
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#1405 create separate files for tests results
  common/github_reports.sh
  pr_testing/test_multiple_prs.sh
  report-pull-request-results.py
  run-pr-comparisons
  templates/js/renderPRTests.js
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-approved
