Repository cms-sw/cms-bot, pull requests merged in 2021-04, with the labels that each got.

#1528 Update reco release profiling
  reco_profiling/profileRunner.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1527 StaticAnalyzer and ClangTidy PR test updates
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1530 add extra merge commits for cmsdist too
  pr_testing/get-merged-prs.py
  pr_testing/test_multiple_prs.sh
  report-pull-request-results.py
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-started

#1531 allow to use special matrix args for gpu,threading etc test
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#1534 New release cycle 12_0_X
  config.map
  forward_ports_map.py
  milestones.py
  releases.map
  releases.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1535 Use IB_WEB_PAGE=1 to allow 11_3 IBs on the page
  config.map
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1533 Update watchers.yaml for ecal-offline
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1532 Addition of DPGs
  categories.py
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#1540 Disable all patatracks
  config.map
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1541 cms-bot: only allow valid characters for runTheMatrix opts
  process_pr.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1538 Only run the cms-esrget clang-tidy check on pull requests.
  pr_testing/test_multiple_prs.sh
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#1542 Arm - decide which IBs to keep/limit
  config.map
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1543 Add new package - IORawData/CSCCommissioning
  categories_map.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1544 Update watchers for ebrondol
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1545 Allow profiling workflow(s) to be specified with PR multiline comment
  pr-schedule-tests
  pr_testing/run-pr-profiling.sh
  process_pr.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending
