Repository cms-sw/cms-bot, pull requests merged in 2021-11, with the labels that each got.

#1657 reco comparisons: add a minimal set of wf maps for D77
  comparisons/matrix_RE.txt
Labels: orp-pending, pending-signatures, tests-approved, externals-pending, requires-external

#1659 reco comparisons: add DNN ID plots for electrons and photons
  comparisons/validate.C
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1658 Add new package for monitoring pixel SoA products
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1660 enable cms deprecated warnings for master's branch PR tests
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1661 ignore depcecated warnings from the summary page
  buildLogAnalyzer.py
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#1662 add docker arch tag if missing
  docker_launcher.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#1663 Reduce watched packages for clelange
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1665 add RecoMuon/MuonRechitClusterProducer to the reco category
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1666 Run wf 101 and 102 in single threaded mode
  RelValArgs.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1667 remove arch part from the docker image
  config.map
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1668 Add Calibration/PPSAlCaRecoProducer to the alca category
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1669 Added watcher giovanni-mocellin
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
