Repository cms-sw/cms-bot, pull requests merged in 2021-02, with the labels that each got.

#1478 Add Francesco Brivio and Helena Malbouisson as alca L2s
  categories.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1480 Update tag versions on non-default branches
  create-new-data-pr.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1481 run relval input test if maxSteps option of runTheMatrix available
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#1479 allow to run full unit tests
  pr_testing/run-pr-qa-unit.sh
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1440 Add functions to get externals stats
  es_utils.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1482 add tau-pog watchers
  groups.yaml
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1483 Remove user from watch list
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1486 Add cvuosalo to watchers file.
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1487 Update my watchlist
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1488 Create ecal-offline group
  groups.yaml
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1490 11634.911 from a short matrix is added to the reco comparison workflow map file
  comparisons/matrix_RE.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1489 unset SINGULARITY_BIND inside singularity
  docker_launcher.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#1491 Add setup-rucio.sh script to the DMWM jenkins setup
  DMWM/install-wmcore.sh
  DMWM/setup-rucio.sh
  DMWM/test-wmcore.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1492 Add sqlite file for MEM_LIVE report for IB and PR testing.
  pr_testing/run-pr-profiling.sh
  run-ib-igprof
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1494 Add eventsetuprecord-get.txt from reports copied for SA
  run_clang_static_analysis
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1485 Reco profiling
  reco_profiling/profileRunner.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1493 Replace Javier with Cecile as l1t manager
  categories.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending
