Repository cms-sw/cms-bot, pull requests merged in 2021-09, with the labels that each got.

#1617 Remove outgoing AlCa L2/L3s
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#1618 remove kpedro88 as upgrade L2
  categories.py
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1619 Treat private header usage as error
  buildLogAnalyzer.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#1621 allow to use pr number to set commit status
  github_utils.py
  mark_commit_status.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#1622 allow to use cmssw-config sources
  pr_testing/get_external_name.sh
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1624 Changes in DQM responsibles
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1625 Adding AlCaDB conveners to the "db" signature
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1626 added wrtabb to watch Egamma related repos
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1627 Get the G4 IBs in the 12_1 queue
  config.map
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1631 create pr relvals mapping file
  pr_testing/run-pr-comparisons
  pr_testing/run-pr-relvals.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1632 removing Chayanit as she stepped down from pdmv L2
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1634 updating watchlist of user:missirol
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1633 Adding Marino Missiroli as HLT L2
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1635 updated list of "configdb-owners"
  gh-teams.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1638 Skip search for ubsan_ib-->non_ubsan
  report-summary-merged-prs
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1641 Adding silviodonato as hlt watcher
  category-watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
