Repository cms-sw/cms-bot, pull requests merged in 2021-03, with the labels that each got.

#1495 Create empty eventsetuprecord-get.txt
  run_clang_static_analysis
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1496 Add Sam Harper in TRIGGER_PR_TESTS
  categories.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1497 Enable multiple workflows for IB profiling job.
  cmssw-pr-test-config
  schedule-additional-tests
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1498 Split profiling workflows the same way for igprof and profiling jobs.
  run-ib-igprof
  schedule-additional-tests
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1499 Export PROFILING_WORKFLOW so Gen.sh will pick it up.
  pr_testing/run-pr-profiling.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1500 reco comparisons: add a set of mappings for D76 similar to existing D49
  comparisons/matrix_RE.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1501 copy igprof mem interim outputs
  reco_profiling/profileRunner.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1502 Use another cmsdist branch for CLANG IB
  config.map
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1503 Static Analyzers script -- copy eventsetuprecord-get.yaml instead
  run_clang_static_analysis
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1504 Copy full workflow directory if there are comparison errors
  comparisons/filter-failed-comparison.py
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#1505 adding PR checks on edm::TriggerResults
  compareTriggerResults
  compareTriggerResultsSummary
  run-pr-comparisons
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1507 Revert 1502 master to clangIB
  config.map
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1508 run trigger comparison in parallel with JR to save some time
  run-pr-comparisons
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#1509 add DataFormats/JetMatching
  categories_map.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1511 Adding Sim directories to watch list for cvuosalo
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1510 add timeout 900s for input relval tests
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1512 Adding user to list of watchers
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1513 Check static analyzer log for warning edm::eventsetup::EventSetupRecord::get called
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#1515 [PPS] Added CalibPPS/TimingCalibration
  categories_map.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1516 added merge commits back in to summary
  pr_testing/_helper_functions.sh
  pr_testing/test_multiple_prs.sh
  report-pull-request-results.py
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#1518 remove smoortga from btv-pog groups.yaml
  groups.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1520 lecriste is not active on CRAB/COMP anymore
  cmsdist_merge_permissions.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1519 add HCALOnly wf to MATRIX_EXTRAS_GPU
  cmssw-pr-test-config
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1521 Enable PR GPU comparisons
  pr_testing/run-pr-relvals.sh
  pr_testing/test_multiple_prs.sh
  run-pr-comparisons
  templates/js/renderPRTests.js
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1517 Add the new packages introduced by #32683
  categories_map.py
Labels: alca-pending, db-pending, externals-pending, heterogeneous-approved, orp-pending, pending-signatures, reconstruction-approved, tests-approved, upgrade-pending

#1522 reco comparisons: add maps for pixel/ecal/hcal-only CPU and GPU workflows
  comparisons/matrix_RE.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1523 add DQM/TrackerRemapper to dqm signature area
  categories_map.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1514 Run custom CMS clang-tidy checks in PR testing.
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-started

#1526 Update watchers.yaml
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending
