Repository cms-sw/cms-bot, pull requests merged in 2021-07, with the labels that each got.

#1576 Add Tamas Vami as alca L2
  categories.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1578 Update of BTV POG package watchers
  groups.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1567 Add step5 in the file size comparison
  pr_testing/run-pr-profiling.sh
  run-ib-igprof
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1580 Use by3 build log analyzer
  build-cmssw-ib-with-patch
  build-fwlite-ib
  buildLogAnalyzer.py
  cmsrep.sh
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1579 for full build get all changes from cmssw
  pr_testing/test_multiple_prs.sh
  report-pull-request-results.py
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1581 for full cmssw avoid running static checks
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-started

#1582 Andrea has not been HLT L2 for a while now
  categories.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1583 Updated release manager list
  categories.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1584 does not send scram b output to jenkins
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1585 update my subscriptions
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1587 Add Kirill Skovpen and Bugra Bilin as new pdmv L2
  categories.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1588 include Utilities/RelMon so that comparison can be run based on PR
  pr_testing/run-pr-comparisons
  pr_testing/setup-pr-test-env.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1590 adding new GEN L2
  categories.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1592 Python2/3 fixes
  report-pull-request-results.py
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1593 Mark RelVals 537, 538 as known failures for aarch64 and ppc64le
  cmssw_known_errors.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1594 reco comparisons: add a map entry for 11634.912 DD4hepDB workflow
  comparisons/matrix_RE.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1595 improve ROOTFileChecks size change message in logRootQA
  logRootQA.py
Labels: externals-pending, orp-approved, pending-signatures, requires-external, tests-approved

#1596 reco release profiling: run igprof after everything else
  reco_profiling/profileRunner.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1597 Update categories_map.py
  categories_map.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1598 reco comparisons: add monitoring for hcal depth in egamma and HGC_ egamma collections
  comparisons/validate.C
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#1600 plots for ticlTrackstersHFNose* products
  comparisons/validate.C
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1601 Update watchers.yaml for makortel
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending
