Repository cms-sw/cms-bot, pull requests merged in 2021-06, with the labels that each got.

#1560 Update Stitched packages to include FWCore/Reflection and FWCore/SharedMemory
  cmssw-subprojcts/Stitched.filter
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1559 reco profiling fixes
  reco_profiling/igprof-fixed.sh
  reco_profiling/profileRunner.py
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1563 avoid clang and static checks output in jenkins log
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1564 Full re-build for cmssw PRs
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#1565 Bring back G4_vecgeom IB for days 1,4
  config.map
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1566 Substitute PPS software person
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1569 Add lines to PR testing summary for Static Analyzers checks for ESR::get and legacy modules usage.
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#1568 Allow Suvankar to trigger the PR test
  categories.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1570 Remove redundant clang-tidy checks. The ESR::get check is implemented in a static analyzer check.
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1571 add mmusich as tracking-pog watcher
  groups.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1574 clean-up tracking-pog configuration in watchers.yaml
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1573 reco comparisons: plots for simTracksters, add wf maps for local tests
  comparisons/matrix_RE.txt
  comparisons/validate.C
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#1575 sort lines of tracking-pog in watchers.yaml
  watchers.yaml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending
