Repository cms-sw/cms-bot, pull requests merged in 2021-01, with the labels that each got.

#1450 Split PR tests; run relvals, addon and profiling as separate jobs
  common/github_reports.sh
  pr-schedule-tests
  pr_testing/_helper_functions.sh
  pr_testing/run-pr-addon.sh
  pr_testing/run-pr-profiling.sh
  pr_testing/run-pr-qa-unit.sh
  pr_testing/run-pr-relvals.sh
  pr_testing/setup-pr-test-env.sh
  pr_testing/test_multiple_prs.sh
  run-pr-comparisons
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1458 include cmssw/arch for all pr results
  pr_testing/test_multiple_prs.sh
  report-pull-request-results.py
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1460 Create master branch on data repo if it doesn't exist
  create-new-data-pr.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1459 run extra relval tests for GPUs
  pr_testing/run-pr-relvals.sh
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#1461 upload gpu results in its own dir
  pr_testing/_helper_functions.sh
  pr_testing/run-pr-relvals.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#1463 run only gpu tests for GPU PR testsing
  cmssw-pr-test-config
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1464 add relval input test
  pr_testing/_helper_functions.sh
  pr_testing/run-pr-relvals.sh
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1462 Update categories_map.py for GBRForest
  categories_map.py
Labels: alca-approved, db-pending, externals-approved, orp-pending, pending-signatures, tests-approved

#1465 Enable PR relval input test
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#1467 Reuse data for GPU PR tests
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#1468 Reduction of the number of categories under 'analysis'
  categories_map.py
Labels: externals-pending, orp-approved, pending-signatures, tests-pending

#1469 Only sort tag names
  create-new-data-pr.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1470 fix addon reporting
  report-pull-request-results.py
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#1471 user dev area message
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#1472 added wf 546, 547 and 548 as known failures
  cmssw_known_errors.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1473 reduce pr summary comment to 3 wf/addon and 5 unit tests
  das-utils/das_client
  pr_testing/run-pr-relvals.sh
  report-pull-request-results.py
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#1474 Added enabkle threading test
  pr-schedule-tests
  pr_testing/_helper_functions.sh
  pr_testing/run-pr-relvals.sh
  pr_testing/test_multiple_prs.sh
  process_pr.py
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#1475 Updating DQM/L2s list
  categories.py
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#1477 test dasgoclient is different version found
  pr_testing/test_multiple_prs.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-started
