Repository cms-sw/cms-bot, pull requests merged in 2022-10, with the labels that each got.

#1848 Update for pixel-offline
  groups.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1849 Added Prasant1993 to watch Egamma related repositories
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1847 add PAT packages to XPOG category
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1852 Adding sameasy to watch egamma and hgcal related repositories
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1857 Disabled 12.2.X and 12.3.X IBs
  config.map
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1858 [Jenkins parser] Fix continuous notifications and code refactor
  jenkins/parser/actions.py
  jenkins/parser/helpers.py
  jenkins/parser/jenkins-parser-job.py
  jenkins/parser/jenkins-retry-job.py
  jenkins/parser/jobs-config.json
  jenkins/parser/paser-config-unittest.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1860 reco comparisons new phase-2 wf numbering after reset around 2022-10-11
  comparisons/matrix_RE.txt
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1861 run-ib-igprof script: check if workflow exists in release
  run-ib-igprof
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1856 Jr comparison validate build once
  comparisons/validateJR.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1859 Update value of profiling wf 39634.21 to 21034.21
  cmssw-pr-test-config
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#1865 Update Phase 2 workflow after renumbering
  reco_profiling/profileRunner.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1866 reco comparisons: map for renano wf 2500.601
  comparisons/matrix_RE.txt
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1868 [Parser] Write parser actions in json file and generate html page accordingly
  jenkins/parser/actions.py
  jenkins/parser/helpers.py
  jenkins/parser/jenkins-parser-job.py
  jenkins/parser/jenkins-parser-monitor-job.py
  jenkins/parser/jenkins-retry-job.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1867 Added nano relval comparison
  cmssw-pr-test-config
  pr_testing/run-pr-comparisons
  templates/js/renderPRTests.js
Labels: orp-pending, pending-signatures, tests-approved, externals-pending, requires-external

#1871 include matrix undefined wrokflow error
  report-pull-request-results.py
Labels: orp-pending, fully-signed, tests-rejected, externals-approved
