Repository cms-sw/cms-bot, pull requests merged in 2022-01, with the labels that each got.

#1685 reco comparisons: add plots for new MTD value maps; add basic monitoring of JECs in pat::Jets
  comparisons/validate.C
Labels: fully-signed, tests-approved, externals-approved, orp-approved

#1684 Update the reco profiling script to support an 8-threaded workflow
  reco_profiling/profileRunner.py
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1686 for external PR tests, make sure to include latest cmssw merges
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending, requires-external

#1688 Adding DQMOffline/MuonDPG to dqm signature
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1687 auto cache input files used by PRs
  pr_testing/run-pr-relvals.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1692 Update categories.py
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1690 Add new muon MVA value from #36179
  comparisons/validate.C
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1693 for full cmssw, make sure to remove release env
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending
