Repository cms-sw/cms-bot, pull requests merged in 2022-07, with the labels that each got.

#1781 add DataFormats/HGCalDigi
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1784 Remove cvuosalo
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1785 use ib tag if USE_IB_TAG test parameters is set
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1786 Add rappoccio to ORP
  categories.py
Labels: pending-signatures, tests-approved, externals-pending, orp-approved

#1788 remove lveldere as fastsim L2
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1789 Remove pieterdavid from watchers.yaml
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1790 Update watchers.yaml
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1791 Update watchers.yaml
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1792 Add new heterogeneous packages
  categories_map.py
Labels: orp-pending, fully-signed, tests-approved, externals-approved

#1794 reco comparisons: 2021 FastSim workflows 13234, 13434
  comparisons/matrix_RE.txt
Labels: orp-pending, fully-signed, tests-approved, externals-approved

#1796 Add new heterogeneous packages
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#1797 New SimPPS/DirectSimProducer subpackage for simulation
  categories_map.py
Labels: fully-signed, tests-pending, externals-approved, orp-approved

#1798 add Jean-Roch and Sebastian as new XPOG.
  categories.py
Labels: fully-signed, tests-pending, externals-approved, orp-approved

#1800 Added DataFormats/TotemReco to reconstruction category
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1799 Add phase-2 D88 geom wf to profileRunner.py
  cmssw-pr-test-config
  reco_profiling/profileRunner.py
Labels: orp-pending, fully-signed, tests-approved, externals-approved
