Repository cms-sw/cms-bot, pull requests merged in 2022-02, with the labels that each got.

#1704 Make sure to sparse checkout CMSSW packages
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started, requires-external

#1705 properly checkout full cmssw for non-master IBs
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, tests-rejected, externals-pending, requires-external

#1707 reco comparisons: add D88 workflows to the reco comparisons map
  comparisons/matrix_RE.txt
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1708 Added user:valsdav to watchers
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1706 Update phase2 profiling workflow to 35234.21
  cmssw-pr-test-config
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1709 Remove EventFilter/Utilities from reco
  categories_map.py
Labels: orp-pending, fully-signed, tests-approved, externals-approved

#1710 Update workflow that needs to be found to make link on IB dashboard for reco profiling
  report-summary-merged-prs
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1711 add `RecoTracker/MkFitCMS` & `RecoTracker/MkFitCore` to reco review category
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1714 reco comparisons: add maps for Run3 data workflows
  comparisons/matrix_RE.txt
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1715 Fix for formating of PR profiling report.
  pr_testing/run-pr-profiling.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending, requires-external

#1713 add 136.889 to pr profiling wf list
  cmssw-pr-test-config
Labels: orp-pending, pending-signatures, externals-pending, tests-started
