Repository cms-sw/cms-bot, pull requests merged in 2022-08, with the labels that each got.

#1802 add the new GEN L2: Meng Lu
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1801 Add Saumya as next AlCaDB L2
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1803 Add CondCore/PPSTimingCalibrationPlugins under db
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1804 Revert "Add CondCore/PPSTimingCalibrationPlugins under db"
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1807 Add more packages to the watch list for Andrea Bocci
  watchers.yaml
Labels: orp-pending, fully-signed, tests-approved, externals-approved

#1808 Updated profiling result checked for to Run3 workflow 11834.21
  report-summary-merged-prs
Labels: orp-pending, fully-signed, tests-approved, externals-approved

#1809 Adding Validation/HLTrigger
  categories_map.py
Labels: orp-pending, fully-signed, tests-pending, externals-approved

#1810 move `MuonAnalysis/MomentumScaleCalibration` from analysis to alca, in absence of an analysis signature
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1811 add Matt as the incoming reco convener
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1774 Added TrackerTFP to category l1
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1812 Add jenkins parser and retry job
  jenkins/parser/jenkins-parser-job.py
  jenkins/parser/jenkins-retry-job.py
  jenkins/parser/jobs-config.json
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1813 Apply path fixes and sanity checks to Jenkins parser job
  jenkins/parser/jenkins-parser-job.py
  jenkins/parser/jenkins-retry-job.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1814 remove qiang from CMSSW L1 and operation
  categories.py
Labels: pending-signatures, tests-approved, externals-pending, orp-approved

#1815 treating threading PR relval the same way as it is done for non-threaded
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, tests-rejected, externals-pending

#1816 Update L2 conveners
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
