Repository cms-sw/cms-bot, pull requests merged in 2022-03, with the labels that each got.

#1717 track reco::Photon::haloTaggerMVAVal
  comparisons/validate.C
Labels: orp-pending, pending-signatures, tests-approved, externals-pending, requires-external

#1718 support das extra options
  das-utils/das_client
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#1716 Generate baseline ref for extra workflows of PR
  jenkins-artifacts
  pr_testing/run-pr-comparisons
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1721 switch reco release profiling to 35234.21
  reco_profiling/igprof-fixed.sh
  reco_profiling/profileRunner.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1723 remove generation of baseline during comparison job
  pr_testing/run-pr-comparisons
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1725 support for adding new type labels
  githublabels.py
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1726 assign DataFormats/L1TMuonPhase2 to l1
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1730 updated watchlist for eyigitba
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1731 use python3or2
  pr_testing/_helper_functions.sh
  pr_testing/get-merged-prs.py
  pr_testing/run-das-query.py
  pr_testing/run-pr-comparisons
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#1732 run voms-proxy with -rfc option
  docker_launcher.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1728 Generate baseline for IB when needed
  cmssw-pr-test-config
  pr_testing/_helper_functions.sh
  pr_testing/run-pr-baseline.sh
  pr_testing/run-pr-comparisons
  pr_testing/run-pr-relvals.sh
  pr_testing/test_multiple_prs.sh
  run-ib-pr-matrix.sh
Labels: orp-pending, fully-signed, tests-approved, externals-approved

#1734 reco comparisons: add a map for 39434.911 D88 DD4hep workflow
  comparisons/matrix_RE.txt
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1736 Update packages to watch for calderona
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1735 drop usage of python3or2 and find the correct python to run
  comparisons/analyzeFWComparison.py
  comparisons/filter-failed-comparison.py
  gen-relval-jobs.py
  jobs/create-relval-jobs.py
  jobs/jobscheduler.py
  jobs/stats.py
  jobs/workflow_final.py
  logUpdater.py
  mark_commit_status.py
  pr_testing/get-merged-prs.py
  pr_testing/run-das-query.py
  pr_testing/run-pr-comparisons
  pr_testing/test_multiple_prs.sh
  report-pull-request-results.py
  run-ib-addon.py
  run-ib-relval.py
  run-ib-testbase.sh
  runTests.py
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1737 add L1 Phase-2 packages
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1738 Replace DQM SW Engineer
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1739 clean github api token usage
  gh-teams.py
  github_utils.py
  process-pull-request
  process_pr.py
  release_notes_collection.py
Labels: orp-pending, pending-signatures, tests-approved, externals-pending
