Repository cms-sw/cms-bot, pull requests merged in 2022-12, with the labels that each got.

#1898 add `CondCore/BasicCondPlugins` to `db` category signature
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1897 Allow relval comparsion to have long and short names
  logRootQA.py
  pr_testing/run-pr-comparisons
Labels: orp-pending, pending-signatures, tests-rejected, externals-pending

#1899 Added E/Gamma L2
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1900 copy external build logs in separate dir
  pr_testing/_helper_functions.sh
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending, requires-external

#1901 Fixes and improvements in nodes-sanity-check job
  jenkins/jenkins-check-nodes.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1902 Update categories_map for #40264
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1903 Update name of pull request memory profiling script.
  pr_testing/run-pr-profiling.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1906 updated `categories_map.py` to include `SiStripMonitorApproximateCluster`
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1907 Add wf `10804.31` and `10805.31` to known errors for release CMSSW_13_* also
  cmssw_known_errors.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1908 Remove jfernan2
  categories.py
Labels: pending-signatures, externals-pending, tests-pending, orp-approved

#1904 Get jenkins queue and push waiting time to elastic search
  parse_jenkins_builds.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
