Repository cms-sw/cms-bot, pull requests merged in 2022-09, with the labels that each got.

#1821 support auto applying code-checks patch
  process_pr.py
  run-pr-code-checks
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1822 [Jenkins parser job] Refactor parser, fix actions and add new errors
  jenkins/parser/jenkins-parser-job.py
  jenkins/parser/jenkins-retry-job.py
  jenkins/parser/jobs-config.json
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1824 Update categories.py for reco L2
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1826 Add AnnikaStein to btv-pog (new RECO contact)
  groups.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1825 updating xpog members
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1829 Removing sscruz
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1827 clean-up TRK DPG / POG categories
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1828 Update Muon POG category and update watched packages for Jan Schulte
  categories.py
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1830 [Jenkins parser job] Add new git error to parser and remove ib-tag-and-schdule
  jenkins/parser/jobs-config.json
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1831 Add `CUDADataFormats/PortableTestObjects` under `heterogeneous`
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#1832 [Jenkins parser job] Skip auto retry if Jenkins already retries
  jenkins/parser/jenkins-parser-job.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1833 Create muon-reco group
  groups.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1834 Turn on notifications for muon-reco group
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1835 Add syuvivida as new DQM L2 convener
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started, dqm-approved

#1837 updated watchlist of user `missirol`
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1838 Watchers: remove swertz from nanoAOD
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1841 [Jenkins parser] Remove new running builds from list of pending builds
  jenkins/parser/jenkins-parser-job.py
  jenkins/parser/jobs-config.json
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1840 Mount /var/run/user and /run/user
  docker_launcher.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1839 Update Spack entries in cvmfsdirtab.sh
  cvmfs/cvmfsdirtab.sh
Labels: orp-pending, pending-signatures, externals-pending, hold, tests-pending

#1842 PR external paths checks test
  monitor_workflow.py
  pr_testing/run-pr-external_checks.sh
  pr_testing/setup-pr-test-env.sh
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1843 run das query for extra workflows too
  pr_testing/run-das-query.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#1844 only test new wfs for das queries
  pr_testing/run-das-query.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started, requires-external

#1846 properly checkfor failing runThematrix
  pr_testing/run-pr-relvals.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending, requires-external

#1845 [Jenkins parser] Add options to force retry and to check concrete error message in all jobs
  jenkins/parser/jenkins-parser-job.py
  jenkins/parser/jobs-config.json
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
