Repository cms-sw/cms-bot, pull requests merged in 2022-06, with the labels that each got.

#1770 When running igprof ensure that compiler include paths are added to ROOT_INCLUDE_PATH
  reco_profiling/profileRunner.py
  run-ib-igprof
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1772 Export ROOT_INCLUDE_PATH so igprof script picks it up
  run-ib-igprof
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1771 Split PR profiling job with multiple workflows into multiple jobs one per workflow.
  pr_testing/run-pr-profiling.sh
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1773 Add scripts to handle Spack installation; generate additional catalog entries for spack
  cvmfs/cms-ib.cern.ch/cvmfsdirtab.sh
  cvmfs/cvmfsdirtab.sh
  spack/backport.sh
  spack/bootstrap.sh
  spack/build.sh
  spack/cvmfsInstall.sh
  spack/install.sh
  spack/singBuild.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1775 Spack: move installation under week number
  cvmfs/cms-ib.cern.ch/cvmfsdirtab.sh
  cvmfs/cvmfsdirtab.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1777 copy ~/tnsnames.ora to workspace see INC3162820 SNOW
  docker_launcher.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#1778 [grid-webhook job] Modify grid id and scheduler to not be input params
  condor/jenkins/connect.sh
  condor/webhook
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1779 Adding Chris to alca watchers
  category-watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1780 move slava77 from reco L2 to tracking-pog, keep the PR test role
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
