Repository cms-sw/cms-bot, pull requests merged in 2022-11, with the labels that each got.

#1875 [Jenkins parser] Improvements in notifications and monitor page cleanup
  jenkins/parser/actions.py
  jenkins/parser/helpers.py
  jenkins/parser/jenkins-parser-job.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1876 added a-kapoor to watch E/Gamma related folders
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1877 [Jenkins parser] Handle `/cvmfs` not mounted on grid nodes
  jenkins/parser/actions.py
  jenkins/parser/helpers.py
  jenkins/parser/jenkins-parser-job.py
  jenkins/parser/jobs-config.json
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1878 [Jenkins parser] Add new git error messages and jobs
  jenkins/parser/jobs-config.json
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1879 cope with improved logging of `addOnTests`
  report-pull-request-results.py
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1883 Add heavy ion workflows to profiling
  reco_profiling/profileRunner.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#1882 [Parser] Add `retryLate` action to delay parser retries
  jenkins/parser/actions.py
  jenkins/parser/helpers.py
  jenkins/parser/jenkins-parser-job.py
  jenkins/parser/jenkins-retry-job.py
  jenkins/parser/jobs-config.json
  jenkins/parser/paser-config-unittest.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1881 [CRAB] Trigger unittest in case of CRAB updates
  common/github_reports.sh
  crab/ib-monitor-crab.sh
  crab/ib-run-pr-crab.sh
  pr_testing/_helper_functions.sh
  pr_testing/test_multiple_prs.sh
  report-pull-request-results.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started, requires-external

#1888 Forward root master updates to root module branch
  forward_ports_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1886 Fix validate in 5.3
  comparisons/validate.C
  comparisons/validateJR.py
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1891 Add Geometry/HGCalTBCommonData under geometry
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1889 switch between AutoLibraryLoader::enable() and FWLiteEnabler::enable()
  comparisons/validateJR.py
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1893 using 13/master as base for forward port to other branches
  forward_ports_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1880 Add config.map entry for Spack build
  config.map
  tests/test_config-map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1895 Add blacklisted nodes to daily summary of nodes status
  jenkins/nodes-status-summary.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1894 Nodes `/afs`, `/cvmfs` and `singularity` sanity check
  jenkins/connect.sh
  jenkins/jenkins-check-nodes.sh
  jenkins/nodes-sanity-check.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
