Repository cms-sw/cms-bot, pull requests merged in 2023-05, with the labels that each got.

#1974 use apptainer command and env
  docker_launcher.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#1975 PR profiling: keep SQL file generated by igprof-analyze
  pr_testing/run-pr-profiling.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started, requires-external

#1977 make cmssw-pr-test-config an executable so that it can set WF based on cmssw version
  cmssw-pr-test-config
  pr_testing/run-pr-profiling.sh
  pr_testing/test_multiple_prs.sh
  run-ib-igprof
  schedule-additional-tests
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#1979 Fix duplicate dictionary check for AVX512 builds
  runTests.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1981 New CMSSW_13_2_X release cycle
  config.map
  forward_ports_map.py
  milestones.py
  releases.map
  releases.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1980 Run jemalloc memory profiling to pull request testing.
  pr_testing/run-pr-profiling.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1983 update GPU PR relvals for cmssw 13 and above
  cmssw-pr-test-config
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#1988 [PARSER] Add cvmfs-cms-stale-lock job
  jenkins/parser/jobs-config.json
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1989 Use python3 for get-pr-branch
  get-pr-branch
  github_utils.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1990 Use --no-rebase for merging branches for PR tests
  pr_testing/_helper_functions.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1992 Add DPGAnalysis/HcalNanoAOD to XPOG
  categories_map.py
Labels: pending-signatures, externals-pending, tests-pending, orp-approved

#1993 Add DPGAnalysis/HcalNanoAOD to CMSSW_LABELS HCAL
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1991 retry input tests multiple times
  pr_testing/retry-command.sh
  run-ib-pr-matrix.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending, requires-external

#1995 Removing hdelanno from watchers.yaml
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1994 Update tag-and-schedule-ibs
  tag-and-schedule-ibs
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1997 Add check for nsys gpu module timings report
  report-summary-merged-prs
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#1998 Fix incorrect gpu report location.
  report-summary-merged-prs
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1999 Update L1 category: remove Cecile
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
