Repository cms-sw/cms-bot, pull requests merged in 2023-03, with the labels that each got.

#1947 Use github api to check for/create CMSSW tag
  github_utils.py
  ib-create-tag.py
  tag-and-schedule-ibs
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1948 Add non-blocking dpg/pog labels to release summary
  release-notes
Labels: orp-pending, fully-signed, tests-pending, externals-approved

#1949 Disable root626 IB
  config.map
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1950 Disable forward porting from master to root626 branch
  forward_ports_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1936 Add test for missing Provides
  pr_testing/cmssw-pr-package.spec
  pr_testing/test-cmssw-provides.sh
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#1952 cleanup test-cmssw-provides; make use of existing cmssw env
  pr_testing/cmssw-pr-package.spec
  pr_testing/test-cmssw-provides.sh
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, fully-signed, externals-approved, tests-started

#1951 Jenkins auto-retry job: retry on singularity mount errors
  jenkins/parser/jobs-config.json
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1953 Update AlCaDB related L2s as of 2023 March
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1954 Logreader: detect more errors (assertion, ASAN)
  logreaderUtils.py
  tests/test_logreaderUtils.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1956 add `RecoTracker/Pixel*` packages to reco signature area
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1957 Restrict unit test to not generate test files in top level project area
  pr_testing/run-pr-qa-unit.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started, requires-external

#1959 Remove Simone Pigazzini from ECAL DPG
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1961 Update watchers.yaml
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1960 New ECAL DPG convener: Jin Wang
  categories.py
  groups.yaml
Labels: pending-signatures, externals-pending, tests-pending, orp-approved

#1962 Drop dependency on PyGithub external package for release build process
  github_utils.py
  report-build-release-status
  report-build-release-status.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#1963 override system commands for special IBs e.g ASAN
  pr_testing/setup-pr-test-env.sh
  run-ib-testbase.sh
  system-overrides.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started
