Repository cms-sw/cms-bot, pull requests merged in 2023-10, with the labels that each got.

#2085 Added PhysicsTools/NanoAODTools under xpog and update watchers
  categories_map.py
  watchers.yaml
Labels: pending-signatures, externals-pending, tests-pending, orp-approved

#2086 Add PonIlya as db watcher
  category-watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2089 Use new el9 buildtime images for IBs
  config.map
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2076 Adding please test function for comp_gcc630.
  cmsdist-comp-pr-process.py
  cmsdist_merge_permissions.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2090 Adding Reyer Band to ecal-offline group
  groups.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2092 allow assigning of categories using package name
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2094 [LXR] Fix checkout-version.py for python3
  lxr/checkout-version.py
Labels: orp-pending, pending-signatures, externals-pending, hold, tests-pending

#2095 Add Martina Malberti as new MTD DPG L2 convener
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2098 Update watchers.yaml for watson-ij
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
