Repository cms-sw/cms-bot, pull requests merged in 2023-08, with the labels that each got.

#2027 Update categories.py for the analysis category
  categories.py
Labels: pending-signatures, externals-pending, tests-pending, orp-approved

#2026 New tool: uniq-errors
  jenkins-jobs/git/git-notify-ib-updates
  shift/libib.py
  shift/report.py
  shift/uniq-errors.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2025 Add D98 wf to profile runner
  reco_profiling/profileRunner.py
Labels: orp-pending, pending-signatures, tests-rejected, externals-pending

#2029 update HCAL contacts
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2031 Adding "node offline" as reason for a job to be in the queue
  parse_jenkins_builds.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2034 Add Ming-Yan to BTV group
  groups.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2035 Add Sen to BTV group
  groups.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2038 Update categories.py with Antonio as release manager
  categories.py
Labels: pending-signatures, externals-pending, tests-pending, orp-approved

#2039 Monitor jenkins queue and offline nodes
  jenkins_monitor_queue.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2041 Update categories_map.py with CondCore/BaseKeyedPlugins
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2040 Get failing relvals from OpenSearch
  get-relval-failures.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2045 Py3: Changes required for all all jenkins-* jobs run on jenkins controller
  es_ib_build_stats.py
  es_utils.py
  jenkins/jenkins-project-report-to-markdown.py
  jenkins/report-jenkins-jobs.py
  jenkins_monitor_queue.py
  parse_jenkins_builds.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2042 Add wf 141.103 per request.
  cmssw-pr-test-config
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2047 add `rovere` as watcher of the HLT Phase-2 menu
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2048 Continue after segfault in igprof so igprof databases are generated. Remove use of tee.
  run-ib-igprof
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2049 github_utils: fix create_team
  github_utils.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2051 add `mmusich` as HLT L2
  categories.py
  gh-teams.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2052 Add 3 new PerfTools packages under core in categories_map.py
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2050 Add ZDC L1T emulator to build bot categories as L1's assignment
  categories_map.py
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2053 Fix bot wrongly stating that there are more errors if there are exactly 4
  report-pull-request-results.py
Labels: orp-pending, fully-signed, tests-pending, externals-approved

#2054 Add CMSSW_13_3_ROOT6DBG_X IB to be built on-demand
  config.map
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2046 Py3: More changes
  add-externals-gh-labels.py
  create-github-hooks
  es/es_git_repo_size.py
  es_ibs_log.py
  fix-backport-labels.py
  gh-teams.py
  jenkins-jobs/git/git-mirror-repository
  jenkins/jenkins-kill-placeholder-job.py
  jenkins_callback.py
  process_pr.py
  trigger_jenkins_job.py
  update-github-hooks-ip
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2059 Update categories.py for ORP
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2061 Remove dpiparo from the CMSSW L1/ORP list
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2062 Added sextonkennedy as CMSSW_L1/ORP
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
