Repository cms-sw/cms-bot, pull requests merged in 2023-12, with the labels that each got.

#2122 Add ib-run-pr-wait-deployment to monitoring
  jenkins/parser/jobs-config.json
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2126 Disable 13.0.X to 13.0.HeavyIon.X forward porting
  forward_ports_map.py
Labels: orp-pending, fully-signed, tests-pending, externals-approved

#2127 look for relval logs with fatal system errors
  report-pull-request-results.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2123 Added l1scouting category
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2129 Add ib-check-invalid-includes to list of jobs monitored
  jenkins/parser/jobs-config.json
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2128 XPOG officers update
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2131 Add subir to upgrade L2
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2135 Use cms-docker issues to schedule and trigger builds for el8/el9 base image changes
  cms-docker-gh-issues.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2134 Added more reactions to special comments; cache the reactions to avoid api calls
  process_pr.py
Labels: orp-pending, fully-signed, tests-pending, externals-approved

#2136 allow to add non-blocking labels for non-cmssw repos
  process-pull-request.py
  process_pr.py
  repo_config.py
  repos/cms_sw/cms_docker/categories.py
  repos/cms_sw/cms_docker/githublabels.py
  repos/cms_sw/cms_docker/repo_config.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2137 add non-blocking labels for assign package comment
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2139 Fix black formatting in `process_pr.py`
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
