Repository cms-sw/cms-bot, pull requests merged in 2023-09, with the labels that each got.

#2063 Add Javier Fernandez as reco convener
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2058 New BTV Conveners
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending, btv-pog-approved

#2064 Switch Phase-2 wf to 25034.21
  cmssw-pr-test-config
  reco_profiling/profileRunner.py
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2057 Migrate scripts to Python3 (part 3)
  cache-pull-request.py
  cmsdist-comp-pr-process.py
  cmsdist_merge_permissions.py
  das-utils/das_cache.py
  das-utils/ib-eos-files.py
  es_cmsdoxygen_apache.py
  es_cmsrep_apache.py
  es_cmssdt_apache.py
  es_doxygen_apache.py
  es_hypernews.py
  es_hypernews_log.py
  es_relval_log.py
  es_utils.py
  forward-pull-requests
  github_utils.py
  jenkins-jobs/es-cmssw-afs-eos.py
  jenkins_monitor_queue.py
  logwatch.py
  mark_commit_status.py
  parse_jenkins_builds.py
  process-build-release-request
  process-error-reports
  process_pr.py
  release-notes
  release_notes_collection.py
  scram-package-monitor-sender
  tag-ib
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2065 Removing outgoing AlCaDB L2s
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2068 remove outgoing TRK POG convener
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2067 add DQMOffline/RecoB to tracking (non-blocking) category
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2072 remove swagata87 as egamma-pog
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2073 Testing buildtime image
  config.map
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2074 New script to process requests for creating cms-data repositories
  cms_static.py
  process-create-data-repo-request
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2078 Add generation of property file for creating data repo
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2079 Use el8 buildtime images for DEVEL (amd64) and ROOTDBG (ppc64le) IBs
  config.map
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2081 Create deleteme.txt
  deleteme.txt
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2083 Adding the new DQM L2 conveners and removing the former software experts
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2070 Add RecoParticleFlow/PFRecHitProducer package
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2071 Add CalibCalorimetry/EBPhase2TPGTools
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2084 Remove former dqm convenor
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
