Repository cms-sw/cms-bot, pull requests merged in 2024-12, with the labels that each got.

#2379 PR Testing: check for warnings also in files not directly touched by PR
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2387 upload dependency file to cmssdt
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2388 Add `DataFormats/HGCalRecHit` to `categories_map.py`
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2389 Disable auto-tests
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2390 Build devel Ibs with additional x86-64-v2
  config.map
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2391 Run cudaComputeCapabilities in addition to nvidia-smi
  pr_testing/setup-pr-test-env.sh
  run-ib-testbase.sh
Labels: orp-pending, fully-signed, externals-approved, tests-started

#2393 Update watchers.yaml
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2394 Update watchers.yaml
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2396 Add "ngt" label
  githublabels.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2397 use x86-64-v2 as additional microarch
  config.map
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2399 use x86-64-v2 as additional microarch
  config.map
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2398 Fix workflow number used to find vtune result
  report-summary-merged-prs.py
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2401 Fix test_multiple_prs to properly reformat cuda warnings
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, tests-rejected, externals-pending, requires-external

#2400 add `EventFilter/Phase2PixelRawToDigi` to `catagories_map.py`
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2403 Only reset signatures for modified files on dirty squash
  process_pr.py
  tests/PRActionData/TestProcessPr.test_partial_reset_dirty_squash.json
  tests/ReplayData/TestProcessPr.test_partial_reset_dirty_squash.txt
  tests/test_process_pr.py
Labels: orp-pending, fully-signed, tests-pending, externals-approved

#2405 Added root 6.34 and disabled root 6.32 IBs
  config.map
  forward_ports_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2395 Implement special handling for draft PRs (and add tests)
  .gitignore
  githublabels.py
  process_pr.py
  tests/PRActionData/TestProcessPr.test_assign.json
  tests/PRActionData/TestProcessPr.test_close.json
  tests/PRActionData/TestProcessPr.test_draft_pr_ask_ready.json
  tests/PRActionData/TestProcessPr.test_draft_pr_assign.json
  tests/PRActionData/TestProcessPr.test_draft_pr_fully_signed.json
  tests/PRActionData/TestProcessPr.test_draft_pr_opened.json
  tests/PRActionData/TestProcessPr.test_draft_pr_ready.json
  tests/PRActionData/TestProcessPr.test_draft_pr_start_test.json
  tests/PRActionData/TestProcessPr.test_draft_pr_updated.json
  tests/PRActionData/TestProcessPr.test_reopen.json
  tests/README.md
  tests/ReplayData/TestProcessPr.test_draft_pr_ask_ready.txt
  tests/ReplayData/TestProcessPr.test_draft_pr_assign.txt
  tests/ReplayData/TestProcessPr.test_draft_pr_fully_signed.txt
  tests/ReplayData/TestProcessPr.test_draft_pr_opened.txt
  tests/ReplayData/TestProcessPr.test_draft_pr_ready.txt
  tests/ReplayData/TestProcessPr.test_draft_pr_start_test.txt
  tests/ReplayData/TestProcessPr.test_draft_pr_updated.txt
  tests/run_pr_tests.sh
  tests/test_process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2409 create cmssw-config toolfile during PR tests
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started, requires-external
