Repository cms-sw/cms-bot, pull requests merged in 2024-06, with the labels that each got.

#2252 Workaround for el9 host and apptainer instance issue
  pr_testing/setup-pr-test-env.sh
  run-ib-testbase.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2255 do not delete data package extra file if package is already in default section
  pr_testing/get_source_flag_for_cmsbuild.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started, requires-external

#2253 Add DQM/PFTasks to dqm category
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2250 add package RecoTracker/LST to reconstruction
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2257 Override local SITECONF if needed
  jobs/run.sh
  pr_testing/setup-pr-test-env.sh
  run-hlt-validation
  run-ib-pr-matrix.sh
  run-ib-testbase.sh
  run-tests-release
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2258 Add ROCM IB
  config.map
  runTests.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2254 revert maxmem_profile change
  pr_testing/test_multiple_prs.sh
  run-ib-pr-matrix.sh
Labels: pending-signatures, tests-approved, externals-pending, orp-approved

#2259 Fix duplicate key in categories.py
  categories.py
Labels: orp-pending, fully-signed, tests-pending, externals-approved

#2261 Improve generate-categories-json.py
  generate-categories-json.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2263 Update list of watched packages in watchers.yaml for mmusich
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2262 Add lxplus tunneling if not CERN domain
  jenkins-artifacts
  logUpdater.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2264 Update list of watched packages for user dinyar
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2265 Get kerberos credentials for LUMI from Jenkins
  lumi/connect.sh
  lumi/get_slot.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2274 Added martinamalberti as watcher
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2275 Remove downloaded RPMs before publishing
  cvmfsInstall.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
