Repository cms-sw/cms-bot, pull requests merged in 2024-01, with the labels that each got.

#2140 docker_launcher: create a separate voms proxy file per job ...
  docker_launcher.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2141 Add a parameter to disable comments on existing GH issues
  create-gh-issue.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2142 docker_launcher: Avoid dasgoclient reading x509 proxy from /tmp
  docker_launcher.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2146 Fix Black style
  github_utils.py
  jobs/create-relval-jobs.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2145 Remove temporary symlinks
  README.md
  cms-jenkins-api
  comment-gh-pr
  compareTriggerResults
  compareTriggerResultsSummary
  create-github-hooks
  deprecate-releases
  es-cleanup-indexes
  es-reindex
  forward-pull-requests
  generate-categories-json
  generate-json-performance-charts
  generate-performance-summary
  get-git-tags
  get-pr-branch
  github-rate-limits
  jenkins-jobs/git/git-mirror-repository
  jenkins-jobs/git/git-notify-ib-updates
  merge-pull-request
  new-release-cycle
  pr-checks/check-pr-files
  pr-checks/check-pr-files.py
  pr-schedule-tests
  pr_testing/run-pr-comparisons
  pr_testing/test_multiple_prs.sh
  process-build-release-request
  process-create-data-repo-request
  process-error-reports
  process-pull-request
  query-and-process-prs
  query-new-pull-requests
  release-notes
  report-cmsdist-pull-request-results
  report-summary-merged-prs
  run-pr-code-checks
  run-user-pr-test
  scram-package-monitor-sender
  scram-package-monitor-timestamps
  tag-ib
  update-github-hooks-ip
  updateVOTags
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2149 Load l2.json from 'repos/repo_name', fallback to cmssw_l2 if not found or empty
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2150 Add Martin Delcourt as Tracker DPG L2
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2151 Fix handling of events with same timestamp
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2152 Add igprof-pp and profiling to SKYLAKEAVX512 releases
  config.map
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2153 Including Geometry/HGCalMapping in categories_map
  categories_map.py
Labels: orp-pending, fully-signed, tests-pending, externals-approved, geometry-approved

#2155 Add L1Trigger/L1TMuonEndCapPhase2 to L1 and Upgrade categories
  categories_map.py
Labels: orp-pending, fully-signed, tests-pending, externals-approved, upgrade-approved, l1-approved

#2157 Add new pixel SoA data formats packages
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2158 Add new pixel SoA data formats packages
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2156 Accept progress labels for cms-docker issues
  process_pr.py
  repos/cms_sw/cms_docker/githublabels.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2159 Allow using `type`, `state` or `build-state` to set labels in GitHub
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
