Repository cms-sw/cms-bot, pull requests merged in 2024-04, with the labels that each got.

#2207 update last processed commit; remove old processed commits
  cmssw_l2/commit.txt
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2208 Add new HeterogeneousTest/Alpaka* packages
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2209 Set up IB for ROOT v6.32
  config.map
  forward_ports_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2210 [ppc64le] Disable 14.1.X PowerPC builds
  config.map
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2212 Fixed typos in bot printout messages
  RelValArgs.py
  checkLogFile.py
  cms-docker-gh-issues.py
  create-gh-issue.py
  create-gh-pr.py
  gh-teams.py
  github_backup.py
  github_utils.py
  ib-pr-workflow-changed.py
  new-release-cycle.py
  process-build-release-request.py
  process-error-reports.py
  process_pr.py
  report-build-release-status.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2214 process_pr: only trigger automatic tests for first L2 signature
  process_pr.py
Labels: orp-pending, fully-signed, tests-pending, externals-approved

#2217 Register L1TMuonOverlapPhase2 into category map.
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2218 Add Afiq Anuar as new EGM L2
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2216 Allow to run extra workflows based on labels of PR
  cmssw-pr-test-config
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending, tracking

#2219 Instead of using release name to enable multiarch use MULTIARCH_OPTS config option
  build-cmssw-ib-with-patch
  build-fwlite-ib
  build-release
  cmsrep.sh
  config.map
  ib-create-tag.py
  jenkins-jobs/check-unused-cmsdist-packages
  pr_testing/test_multiple_prs.sh
  tests/test_config-map.py
  upload-release
Labels: orp-pending, pending-signatures, externals-pending, tests-started, requires-external

#2220 Add upgrade to L1Trigger/L1TMuonOverlapPhase2
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
