Repository cms-sw/cms-bot, pull requests merged in 2024-09, with the labels that each got.

#2322 HCAL DQM Update watchers.yaml
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2317 Update MUO POG L2s
  categories.py
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2324 add `RecoVertex/PixelVertexFinding` to reco L2 signature area
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2325 do not start extra process for relval comparison
  pr_testing/run-pr-comparisons
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2320 Compare maxmem_profile.txt for each workflow with comparison release
  pr_testing/run-pr-comparisons
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2323 [RFC] Disable checking for number of modified files in non-cmssw repos
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, hold, tests-pending

#2327 ib-create-tag: fix searching for last commit to include in IB
  ib-create-tag.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2329 remove vlimant form xpog category
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2328 Add max mem comparison script and check stderr for message the threashdold was exceeded.
  comparisons/compare-maxmem.py
  pr_testing/run-pr-comparisons
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2310 Update GPU RelVals to 2024 wfs
  cmssw-pr-test-config
Labels: orp-pending, fully-signed, tests-approved, externals-approved

#2331 remove slava77 from tracking POG category
  categories.py
Labels: orp-pending, fully-signed, tests-pending, externals-approved

#2332 Add remaining framework people to core-team
  gh-teams.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2333 Update simulation L2
  categories.py
  category-watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2337 Add Moanwar to upgrade category
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2338 Region parameter was not respected - also usage typos
  s3/s3-upload-policy.sh
  s3/s3utils.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2340 Update categories.py with new TauPOG L2
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2335 Maximum comparison: report step1 das query to align steps for all workflows, report summary as html table
  comparisons/compare-maxmem-summary.py
  comparisons/compare-maxmem.py
  pr_testing/run-pr-comparisons
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2341 Fix one misspelled word in Jenkins parser
  jenkins/jenkins-check-nodes.sh
  jenkins/parser/actions.py
  jenkins/parser/jenkins-parser-job.py
  jenkins/parser/jenkins-parser-monitor-job.py
  jenkins/parser/jenkins-retry-job.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2342 avoid duplication in l2 list
  process_pr.py
  tests/PRActionData/TestProcessPr.test_assign.json
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
