Repository cms-sw/cms-bot, pull requests merged in 2024-10, with the labels that each got.

#2344 Maxmem profile summary: Swap the order of pull request and baseline in table entries
  comparisons/compare-maxmem-summary.py
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2347 Small adjustments to package2category script
  package2category.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2348 Fix typo in profiling summary link.
  pr_testing/run-pr-profiling.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2349 Uncomment memory profiling.
  pr_testing/run-pr-profiling.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2351 [py312][2/3] fixing SyntaxWarning warnings
  das-utils/das_cache.py
  das-utils/ib-eos-files.py
  es/es_close_indexes.py
  es_cmsdoxygen_apache.py
  es_cmssdt_apache.py
  es_doxygen_apache.py
  es_ib_build_stats.py
  es_ibs_log.py
  es_utils.py
  fix-igprof-sql.py
  github_backup.py
  github_utils.py
  jenkins/jenkins-kill-placeholder-job.py
  jenkins/jenkins-project-report-to-markdown.py
  jenkins/parser/actions.py
  jenkins/parser/jenkins-retry-job.py
  jenkins/parser/paser-config-unittest.py
  jobs/create-relval-jobs.py
  jobs/workflow_final.py
  lizard-processing/src/lizard_to_html.py
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2350 [py312][1/3] fixing SyntaxWarning warnings
  RelValArgs.py
  archive/create_json.py
  archive/es_hypernews.py
  archive/es_hypernews_log.py
  archive/find-changed-workflows.py
  archive/generate-performance-summary.py
  archive/getWorkflowStatsFromES.py
  archive/github_get_file_changes.py
  archive/ib-pr-workflow-changed.py
  buildLogAnalyzer.py
  cache-pull-request.py
  cms_static.py
  cmsdist-comp-pr-process.py
  cmsdist_merge_permissions.py
  cmsutils.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2353 Remove myself from groups.yaml
  groups.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2354 Run `hltPhase2UpgradeIntegrationTests` in IB, add option to run hlt p2 integration script for PRs
  pr_testing/run-pr-hlt-p2-integration.sh
  pr_testing/test_multiple_prs.sh
  process_pr.py
  run-hlt-validation
Labels: orp-pending, fully-signed, tests-pending, externals-approved

#2356 [hlt-p2-int] Control the parallel running processes
  pr_testing/run-pr-hlt-p2-integration.sh
  run-hlt-validation
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2357 Removing this account from more lists
  create-gh-issue.py
  groups.yaml
  repos/iarspider_cmssw/cmssw/categories.py
  repos/iarspider_cmssw/cmssw/groups.yaml
  repos/iarspider_cmssw/cmssw/watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2359 Update ibeos-lfn-sort: typo
  das-utils/ibeos-lfn-sort
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2358 add some debug statements for das client and ibeos-lnf-sort
  das-utils/das_client
  pr_testing/setup-pr-test-env.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2360 Update of L2 PRO POG conveners
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2364 update ppd, pdmv, dqm categories
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending, dqm-pending, pdmv-approved, ppd-approved
