Repository cms-sw/cms-bot, pull requests merged in 2024-07, with the labels that each got.

#2278 Add L1TriggerScouting/OnlineProcessing to DAQ and cleanup old packages
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2279 Relax chk-invalid-headers checks to match SCRAM rules:
  chk-invalid-headers.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2276 Added L1scouting OnlineProcessing category
  categories_map.py
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending, l1-approved

#2280 Remove data workflows from profiling in PRs
  cmssw-pr-test-config
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2273 Move checking git repo size change to a separate test
  pr_testing/test_multiple_prs.sh
  run-pr-code-checks
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2283 Run git repo size check only for devel release/prod arch
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2284 allow profiling workflow extra args
  cmssw-pr-test-config
  pr_testing/run-pr-profiling.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2281 PR test: Run sourcing of cmsset_default.sh for el6-el9
  pr_testing/_helper_functions.sh
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2285 Add delay between sending opensearch requests
  es_utils.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2286 update github create hook: include name and data in to url
  create-github-hooks.py
  github_hooks_config.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2272 Add README for running/recording process_pr tests
  tests/README.md
  tests/run_pr_tests.sh
  tests/test_process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2198 Limit how many files can be changed in a PR
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, hold, tests-pending

#2288 add Vlimant to PPD
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2289 allow to add changes-dataformats labels by an explicit comment by L2/ORP
  githublabels.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2290 add changes-dataformats label if PR touches classes_def.xml
  categories_map.py
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2291 add Mario to tracking POG
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2292 Allow closing/reopening a PR even if there are too many commits or changed files
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2293 Add VourMa as watcher of the HLT Phase-2 menu
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2294 Added @mandrenguyen as new ORP manager
  categories.py
Labels: pending-signatures, externals-pending, tests-pending, orp-approved

#2282 Update workflows to monitor in PR profiling
  cmssw-pr-test-config
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2295 Update gpu workflows for CMSSW 14.x
  cmssw-pr-test-config
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2297 Add on-demand NONLTO build for 14_0
  config.map
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2298 updated gen conveners
  categories.py
Labels: pending-signatures, externals-pending, tests-pending, orp-approved

#2299 make a copy of /etc/tnsnames.ora before starting the container
  docker_launcher.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2300 Update of watchers.yaml for @forthommel
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2303 Adding YaoYao - new ML Prod L3
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
