Repository cms-sw/cms-bot, pull requests merged in 2024-11, with the labels that each got.

#2365 use baseline for denominator in percentage diff in resources-diff.py
  comparisons/resources-diff.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2367 external PR tests: include/deploy extra available tools too
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending, requires-external

#2369 remove myself from watchers.yaml
  watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2370 LUMI new singcvmfs setup
  lumi/get_slot.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2366 PR profiling: Run IB profiling on same VM
  pr_testing/run-pr-profiling.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2372 Simplify code for getting current timezone; fix timestamp format
  github_utils.py
  ib-create-tag.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2361 PR Testing: check for warnings also in files not directly touched by PR
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2373 Unify REAL_ARCH for PR/baseline relvals
  cms_static.py
  cmsrep.sh
  logRootQA.py
  pr_testing/run-pr-comparisons
  pr_testing/test_multiple_prs.sh
  report-summary-merged-prs.py
  schedule-additional-tests
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2377 Set TMPDIR in docker_launcher.sh if not set already
  docker_launcher.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2371 Resources comparison: Compare absolute difference of fraction of total time per module
  cmssw-pr-test-config
  comparisons/resources-diff.py
  pr_testing/run-pr-profiling.sh
  report-summary-merged-prs.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2380 Run scram build commands under /usr/bin/time
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2374 use AuthenticAMD for PR/baselibe relvals
  cmsrep.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2383 Fix formatting in forward_ports_map.py
  forward_ports_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2382 Only report each RelVal failure once; fix formatting
  report-pull-request-results.py
Labels: orp-pending, pending-signatures, tests-rejected, externals-pending

#2385 automatically approve operations on tests passed
  categories.py
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2384 Parse package info data and push it to OpenSearch
  push-pkg-info.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
