Repository cms-sw/cms-bot, pull requests merged in 2024-05, with the labels that each got.

#2221 ignore ref wf failures if Pr tests did not run that wf
  pr_testing/run-pr-comparisons
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2222 Add cms-containers-run-cmssw-test job to cleanup-cmssdt script
  cleanup-cmssdt
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2223 Add cell for Vtune link
  report-summary-merged-prs.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2224 Vtune link has undefined for arch
  report-summary-merged-prs.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2225 Use * instead of WORKFLOW so vtune log can be found
  report-summary-merged-prs.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2226 use relvals after PR merge for input tests
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending, requires-external

#2227 use 4 week indexes for ES
  cmssw_known_errors.py
  cmsutils.py
  report-summary-merged-prs.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2232 Run hlt timing test for master IB
  config.map
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2233 Keep HLT timing results indefinitely
  cleanup-cmssdt
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2234 Add hlt timings test to report-summary-merged-prs.py
  report-summary-merged-prs.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2235 Update report-summary-merged-prs.py
  report-summary-merged-prs.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2231 Parse out maxmem-profile info from relval logs and write to a file
  run-ib-pr-matrix.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2242 Adding Felipe Silva for XPOG signature
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2241 Add CondTools/DeDx to AlCa and DB categories
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2240 Add option to run hlt p2 timing script for PRs
  pr_testing/run-pr-hlt-p2-timing.sh
  pr_testing/test_multiple_prs.sh
  process_pr.py
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2246 Add `PhysicsTools/XGBoost` to ml category
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2244 Connect Jenkins agent to LUMI slots
  lumi/connect.sh
  lumi/get_slot.sh
  lumi/jenkins_java.sh
  lumi/update_image.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2247 Use different paths for each LUMI slot in Jenkins
  lumi/get_slot.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2249 Add FWCore/TestModules to be signed by core
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
