Repository cms-sw/cms-bot, pull requests merged in 2025-05, with the labels that each got.

#2491 Replace ROOT634 IBs with ROOT636
  config.map
  forward_ports_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2492 Remove Sandra from the AlCaDB signatures
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2488 Fix signing labels for orp-only issues
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2487 Nano Comparison: Keep WF full name and forward it to .json files
  pr_testing/run-pr-comparisons
Labels: fully-signed, tests-approved, externals-approved, orp-approved, requires-external

#2496 Automatically run code checks for branches that track devel branch
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2493 ib-create-tag: do not fail if trying to create a tag that already exists
  ib-create-tag.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2501 updated workflow regexp to allow names workflow list
  pr_testing/test_multiple_prs.sh
  process_pr.py
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2503 Remove MKLDNN0 build which is no longer needed
  config.map
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2504 add `HLTrigger/NGTScouting` to hlt signature area
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2495 Make static analyzer errors more visible
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending, requires-external

#2506 do not pass --gpu required option when checking for already run relvals
  pr_testing/run-pr-relvals.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2509 Revert "Remove MKLDNN0 build which is no longer needed"
  config.map
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2512 Do not create bot/x/ack status
  process_pr.py
  tests/PRActionData/TestProcessPr.test_abort.json
  tests/PRActionData/TestProcessPr.test_assign.json
  tests/PRActionData/TestProcessPr.test_backport.json
  tests/PRActionData/TestProcessPr.test_backport_already_seen.json
  tests/PRActionData/TestProcessPr.test_close.json
  tests/PRActionData/TestProcessPr.test_cmsdist_start_tests.json
  tests/PRActionData/TestProcessPr.test_code_check_approved.json
  tests/PRActionData/TestProcessPr.test_draft_pr_ask_ready.json
  tests/PRActionData/TestProcessPr.test_draft_pr_assign.json
  tests/PRActionData/TestProcessPr.test_draft_pr_fully_signed.json
  tests/PRActionData/TestProcessPr.test_draft_pr_opened.json
  tests/PRActionData/TestProcessPr.test_draft_pr_ready.json
  tests/PRActionData/TestProcessPr.test_draft_pr_start_test.json
  tests/PRActionData/TestProcessPr.test_draft_pr_updated.json
  tests/PRActionData/TestProcessPr.test_grant.json
  tests/PRActionData/TestProcessPr.test_hold.json
  tests/PRActionData/TestProcessPr.test_ignore_rejected_invalid.json
  tests/PRActionData/TestProcessPr.test_ignore_rejected_valid.json
  tests/PRActionData/TestProcessPr.test_ignore_smth.json
  tests/PRActionData/TestProcessPr.test_invalid_test_params.json
  tests/PRActionData/TestProcessPr.test_invalid_type.json
  tests/PRActionData/TestProcessPr.test_merge_pr.json
  tests/PRActionData/TestProcessPr.test_new_cmsdist_pr.json
  tests/PRActionData/TestProcessPr.test_reopen.json
  tests/PRActionData/TestProcessPr.test_run_test_params.json
  tests/PRActionData/TestProcessPr.test_sign_core.json
  tests/PRActionData/TestProcessPr.test_start_tests.json
  tests/PRActionData/TestProcessPr.test_test_all_params.json
  tests/PRActionData/TestProcessPr.test_test_for_arch.json
  tests/PRActionData/TestProcessPr.test_test_for_quearch.json
  tests/PRActionData/TestProcessPr.test_test_for_queue.json
  tests/PRActionData/TestProcessPr.test_test_params.json
  tests/PRActionData/TestProcessPr.test_test_using_addpkg.json
  tests/PRActionData/TestProcessPr.test_test_using_full.json
  tests/PRActionData/TestProcessPr.test_test_with_pr.json
  tests/PRActionData/TestProcessPr.test_test_workflow.json
  tests/PRActionData/TestProcessPr.test_testparams_all_params.json
  tests/PRActionData/TestProcessPr.test_tests_passed.json
  tests/PRActionData/TestProcessPr.test_tests_rejected.json
  tests/PRActionData/TestProcessPr.test_unassign.json
  tests/PRActionData/TestProcessPr.test_unhold.json
  tests/PRActionData/TestProcessPr.test_valid_type.json
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2514 temp fix for running PR code-checks: explicitly set --gcc-toolchain
  run-pr-code-checks
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
