Repository cms-sw/cms-bot, pull requests merged in 2025-09, with the labels that each got.

#2531 Add more GPU flavors (see cms-sw/cmssw#48545)
  gpu_flavors.txt
  pr-schedule-tests
  pr_testing/_helper_functions.sh
  pr_testing/run-pr-unittests.sh
  pr_testing/test_multiple_prs.sh
  process_pr.py
  run-ib-pr-matrix.sh
  tests/PRActionData/TestProcessPr.test_abort.json
  tests/PRActionData/TestProcessPr.test_cmsdist_start_tests.json
  tests/PRActionData/TestProcessPr.test_draft_pr_ready.json
  tests/PRActionData/TestProcessPr.test_draft_pr_start_test.json
  tests/PRActionData/TestProcessPr.test_ignore_smth.json
  tests/PRActionData/TestProcessPr.test_run_test_params.json
  tests/PRActionData/TestProcessPr.test_start_tests.json
  tests/PRActionData/TestProcessPr.test_test_all_params.json
  tests/PRActionData/TestProcessPr.test_test_for_arch.json
  tests/PRActionData/TestProcessPr.test_test_for_quearch.json
  tests/PRActionData/TestProcessPr.test_test_for_queue.json
  tests/PRActionData/TestProcessPr.test_test_using_addpkg.json
  tests/PRActionData/TestProcessPr.test_test_using_full.json
  tests/PRActionData/TestProcessPr.test_test_with_pr.json
  tests/PRActionData/TestProcessPr.test_test_workflow.json
  tests/PRActionData/TestProcessPr.test_testparams_all_params.json
  tests/PRActionData/TestProcessPr.test_tests_passed.json
  tests/ReplayData/TestProcessPr.test_testparams_all_params.txt
Labels: orp-pending, fully-signed, tests-approved, externals-approved, requires-external

#2556 Update generator list
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2553 Added extra nvidia gpus h100 and l40s
  gpu_flavors.txt
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2557 run relvals for devel/root6 with cmsTraceFunction --abort
  RelValArgs.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2560 fwyzard: watch core EventFilter packages
  watchers.yaml
Labels: orp-pending, fully-signed, externals-approved, tests-started

#2558 Allow making some GPU flavors on-demand
  cmssw-pr-test-config
  gpu_flavors_ondemand.txt
  pr-schedule-tests
  pr_testing/run-pr-relvals.sh
  pr_testing/test_multiple_prs.sh
  process_pr.py
  run-ib-pr-matrix.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2572 Tracking POG-related updates
  categories.py
  groups.yaml
Labels: orp-pending, fully-signed, tests-pending, externals-approved

#2576 Validate jr processing history msg
  comparisons/validateJR.py
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2579 Change the production compiler to gcc13 in 16_0_X
  config.map
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2578 Promote the W7900 from optional to run automatically
  gpu_flavors.txt
  gpu_flavors_ondemand.txt
Labels: orp-pending, pending-signatures, tests-approved, externals-pending
