Repository cms-sw/cms-bot, pull requests merged in 2025-02, with the labels that each got.

#2428 Fix printout typoes
  es_relval_log.py
  generate-class-version.sh
  jenkins/parser/actions.py
  process_pr.py
  report-summary-merged-prs.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2427 fix header consistency check: ignore headers with #error
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2429 Fix installation of CUDA to cvcms-restricted
  cuda/install-cuda.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2431 cmsBuild from V00-33 and above support --define option
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2432 Scouting Offline DQM developments for 2025
  categories_map.py
Labels: pending-signatures, tests-approved, externals-pending, orp-approved, dqm-approved

#2435 :sparkles: Begin trying CI on cmsbot from Eric100911/collatz
  repos/Eric100911/collatz/repo_config.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2436 :wrench: Updated secret
  repos/Eric100911/collatz/repo_config.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2438 Reconnect node on 'Cannot run program "/bin/bash"'
  jenkins/parser/jobs-config.json
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2439 Add 'cuda' label; detect AMD gpu and assign 'rocm' label
  jenkins/system-info.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2442 Add `FWIO/RNTuple` package for `core`
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2443 Allow core-team to have write access to framework-team repo
  gh-teams.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2441 Account for new formatting of FastTimerService json files.
  comparisons/resources-diff.py
  pr_testing/run-pr-profiling.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending
