Repository cms-sw/cms-bot, pull requests merged in 2025-01, with the labels that each got.

#2410 Remove silviodonato from HLT watchers
  category-watchers.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2411 Add Henriette Petersen as Tracker DPG convener
  categories.py
  groups.yaml
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2402 enable multi-targets if requested via PR
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2412 Add tables for the additional MaxMemoryPreload-reported quantities
  comparisons/compare-maxmem-summary.py
  comparisons/resources-diff.py
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2413 Add HeterogeneousCore/AlpakaMath package to heterogeneous
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2414 Fix bug in resources diff script
  comparisons/resources-diff.py
Labels: orp-pending, fully-signed, tests-approved, externals-approved

#2416 Set X509_USER_KEY and X509_USER_CERT for lumi …
  docker_launcher.sh
  lumi/get_slot.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2408 Add hyperlinks to build log
  buildLogAnalyzer.py
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2415 PR profiling: remove running of IgProf for memory and cpu profiling and remove running of JeProf for memory profiling.
  comparisons/resources-diff.py
  pr_testing/run-pr-profiling.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2419 Send stacktrace to es
  es_relval_log.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2420 Assign DPGAnalysis/Phase2L1TNanoAOD to L1 and XPOG
  categories_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending, l1-approved, xpog-approved

#2422 Allow overriding path to github-token via env variable
  lumi/get_slot.sh
  repo_config.py
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2421 Send stacktraces from unit tests to ES
  es_ibs_log.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2423 Replace 15.0 ROOT634 IBs with RNTUPLE
  config.map
  forward_ports_map.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2424 send_jenkins_artifacts: ignore source user, group and permissions
  jenkins-artifacts
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2425 fixing bot pr relvals for IBs for which comparison is not run
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2426 improve running of pr relvals
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started
