Repository cms-sw/cms-bot, pull requests merged in 2025-03, with the labels that each got.

#2445 override voms-cms-auth.app.cern.ch to avoid using voms-cms-auth.app.cern.ch
  docker_launcher.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2448 compare-maxmem-summary.py: Swap the order of pull request and baseline entries
  comparisons/compare-maxmem-summary.py
Labels: orp-pending, fully-signed, tests-approved, externals-approved

#2446 resources-diff.py: Fix order of diff in legend. Fix order of pr and ib data in Job line
  comparisons/resources-diff.py
  pr_testing/run-pr-profiling.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2418 Run PR gpu utests/relvals on both CUDA and ROCm GPUs
  cleanup-cmssdt
  cmssw-pr-test-config
  gpu_flavors.txt
  pr_testing/_helper_functions.sh
  pr_testing/run-pr-comparisons
  pr_testing/run-pr-relvals.sh
  pr_testing/run-pr-unittests.sh
  pr_testing/test_multiple_prs.sh
  process_pr.py
  report-pull-request-results.py
  run-ib-pr-matrix.sh
  tests/PRActionData/TestProcessPr.test_abort.json
  tests/PRActionData/TestProcessPr.test_draft_pr_ready.json
  tests/PRActionData/TestProcessPr.test_draft_pr_start_test.json
  tests/PRActionData/TestProcessPr.test_run_test_params.json
  tests/PRActionData/TestProcessPr.test_start_tests.json
  tests/PRActionData/TestProcessPr.test_tests_passed.json
  tests/test-requirements.txt
Labels: orp-pending, pending-signatures, tests-rejected, externals-pending

#2455 End of term, adding new L1T conveners
  categories.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2453 override cpu count via JENKINS_AGENT_CORES
  cmsutils.py
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2457 override nproc if JENKINS_AGENT_CORES is set
  docker_launcher.sh
  system-tools/nproc/nproc
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2458 Pass "--gpu required" when running RelVals on GPU
  pr_testing/_helper_functions.sh
  pr_testing/run-pr-relvals.sh
  run-ib-pr-matrix.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2459 Fix ENABLE_BOT_TESTS
  pr_testing/test_multiple_prs.sh
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2460 Fix #2459 (no need to redefine IFS)
  pr_testing/test_multiple_prs.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2461 Extra tests: accept 'high_stats', not 'high-stats'
  process_pr.py
Labels: orp-pending, fully-signed, tests-pending, externals-approved

#2466 process_pr: put code that preprocesses comment text into separate function
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2463 Add Raffaella Tramontano as EGM convener
  categories.py
Labels: pending-signatures, externals-pending, tests-pending, orp-approved

#2465 process_pr: add tests for test options
  process_pr.py
  tests/PRActionData/TestProcessPr.test_test_all_params.json
  tests/PRActionData/TestProcessPr.test_test_for_arch.json
  tests/PRActionData/TestProcessPr.test_test_for_quearch.json
  tests/PRActionData/TestProcessPr.test_test_for_queue.json
  tests/PRActionData/TestProcessPr.test_test_using_addpkg.json
  tests/PRActionData/TestProcessPr.test_test_using_full.json
  tests/PRActionData/TestProcessPr.test_test_with_pr.json
  tests/PRActionData/TestProcessPr.test_test_workflow.json
  tests/PRActionData/TestProcessPr.test_testparams_all_params.json
  tests/ReplayData/TestProcessPr.test_test_all_params.txt
  tests/ReplayData/TestProcessPr.test_test_for_arch.txt
  tests/ReplayData/TestProcessPr.test_test_for_quearch.txt
  tests/ReplayData/TestProcessPr.test_test_for_queue.txt
  tests/ReplayData/TestProcessPr.test_test_using_addpkg.txt
  tests/ReplayData/TestProcessPr.test_test_using_full.txt
  tests/ReplayData/TestProcessPr.test_test_with_pr.txt
  tests/ReplayData/TestProcessPr.test_test_workflow.txt
  tests/ReplayData/TestProcessPr.test_testparams_all_params.txt
  tests/test_process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2464 process_pr: use logging instead of print
  github_utils.py
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
