Repository cms-sw/cms-bot, pull requests merged in 2025-08, with the labels that each got.

#2545 Run all Run4 HLT menu flavours.
  pr_testing/run-pr-hlt-p2-integration.sh
  run-hlt-validation
Labels: orp-pending, fully-signed, tests-approved, externals-approved, ngt

#2546 use prefer using python3 for monitoring script
  RelValArgs.py
Labels: orp-pending, pending-signatures, tests-approved, externals-pending, requires-external

#2547 Detect and report invalid workflow lists
  pr_testing/_helper_functions.sh
  pr_testing/run-pr-relvals.sh
  run-ib-pr-matrix.sh
Labels: orp-pending, fully-signed, tests-pending, externals-approved

#2548 pileup mapping script added
  pullPileup.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending
