Repository cms-sw/cms-bot, pull requests merged in 2025-04, with the labels that each got.

#2440 Automatically kill stuck PR tests and report back
  kill-stuck-pr-test.sh
  parse_jenkins_builds.json
  parse_jenkins_builds.py
  pr_testing/_helper_functions.sh
  pr_testing/run-pr-comparisons
  pr_testing/run-pr-relvals.sh
  pr_testing/run-pr-unittests.sh
  update-commit-statues-matching.py
Labels: orp-pending, pending-signatures, tests-rejected, externals-pending

#2467 Put IgProf back in. Remove running profiling on IB only.
  pr_testing/run-pr-profiling.sh
Labels: fully-signed, tests-approved, externals-approved, orp-approved, requires-external

#2469 Add _MKLDNN0_ build with Tensorflow built with MKLDNN disabled.
  config.map
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2472 Ignore non-ascii symbols instead of replacing them with question mark
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2473 Fix report filename for PR tests
  pr_testing/run-pr-relvals.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2474 make use of IB_TEST_TYPE for IB relvals flags
  RelValArgs.py
  pr_testing/_helper_functions.sh
Labels: orp-pending, pending-signatures, tests-rejected, externals-pending

#2468 IB relvals: get number of supported GPUs instead of hardcoding it
  cmsutils.py
  jobs/jobscheduler.py
  run-ib-relval.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started

#2471 Do not process closed PRs
  process_pr.py
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2475 Configure IB igprof job to exit ERR when a segfault occurs instead of continuing.
  run-ib-igprof
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2477 Update workflows to use ubuntu-latest
  .github/workflows/test-changes.yaml
  .github/workflows/test-process-pr.yaml
  tests/run_pr_tests.sh
Labels: orp-pending, pending-signatures, externals-pending, tests-pending

#2479 check for errors in the `hlt-p2-integration.log`
  pr_testing/run-pr-hlt-p2-integration.sh
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#2482 Adjust to changed location of inspectNanoFile.py
  pr_testing/run-pr-comparisons
Labels: orp-pending, fully-signed, tests-approved, externals-approved

#2485 Entry for BPHNano in categories_map.py
  categories_map.py
Labels: orp-pending, fully-signed, tests-pending, externals-approved

#2480 Add extra logging to try and debug ib-create-tag.py failing
  ib-create-tag.py
Labels: orp-pending, fully-signed, tests-pending, externals-approved
